AirlinesWeb/Controllers/AirlinesController.cs
using Airlines.Business.DTOs;
using Airlines.Business.Interfaces;
using AirlinesWeb.Extensions;
using AirlinesWeb.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AirlinesWeb.Controllers;
public class AirlinesController : Controller
{
    private readonly IAirlineService _airlineService;
    private readonly int _PAGE_SIZE = 7;
    public AirlinesController(IAirlineService airlineService)
    {
        _airlineService = airlineService;
    }
    public async Task<IActionResult> Index(AirlineDTO airlineDTO, string? search, string? isAfter2008, int page = 1)
    {

        var airlinesListAndFormModel = await _CreateAirlinesListAndFormModelByQueries(airlineDTO, search, isAfter2008, page);
        return View(airlinesListAndFormModel);
    }

    [HttpPost]
    public async Task<IActionResult> Index([FromForm] AirlineDTO airlineDTO)
    {
        if (!ModelState.IsValid)
        {
            return View(await _CreateAirlinesListAndFormModelByQueries(airlineDTO, null, null));
        }

        try
        {
            await _airlineService.AddAirline(airlineDTO);
        }
        catch (Exception e)
        {
            ViewData["errMessage"] = e.Message;
        }

        var airlinesListAndFormModel = await _CreateAirlinesListAndFormModelByQueries(new AirlineDTO(), null, null);
        return View(airlinesListAndFormModel);
    }

    private async Task<AirlinesListAndFormModel> _CreateAirlinesListAndFormModelByQueries(AirlineDTO airlineDTO, string? search, string? isAfter2008, int page = 1)
    {
        var airlinesQuery = this._airlineService
            .GetAll();

        if (search != null)
        {
            airlinesQuery = airlinesQuery
                 .Where(a => a.Name.Contains(search));
        }

        if (isAfter2008 != null)
        {
            airlinesQuery = airlinesQuery
                .Where(a => a.Founded.Year > 2008);
        }

        int totalCount = await airlinesQuery.CountAsync();
        int totalPages = (int)Math.Ceiling(((decimal)totalCount / _PAGE_SIZE));
        var paginationModel = new PaginationModel(totalCount, totalPages, page);

        airlinesQuery = airlinesQuery.Skip((page - 1) * _PAGE_SIZE).Take(_PAGE_SIZE);

        var airlines = await airlinesQuery.ToModel().ToListAsync();
        return new AirlinesListAndFormModel(airlines, paginationModel, airlineDTO);
    }


}

AirlinesWeb/Controllers/AirportsController.cs
using Airlines.Business.DTOs;
using Airlines.Business.Interfaces;
using AirlinesWeb.Extensions;
using AirlinesWeb.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;


namespace AirlinesWeb.Controllers;
public class AirportsController : Controller
{
    private readonly IAirportService _airportService;
    public AirportsController(IAirportService airportService)
    {
        this._airportService = airportService;
    }

    public async Task<IActionResult> Index(AirportDTO airportDTO, string? search)
    {
        return View(await _CreateAirportsListAndFormModel(airportDTO));
    }

    [HttpPost]
    public async Task<IActionResult> Index([FromForm] AirportDTO airportDTO)
    {
        if (!ModelState.IsValid)
        {
            return View(await _CreateAirportsListAndFormModel(airportDTO));
        }

        try
        {
            await this._airportService.AddAirport(airportDTO);
        }
        catch (Exception e)
        {
            ViewData["errMessage"] = e.Message;
        }

        return View(await _CreateAirportsListAndFormModel(new AirportDTO()));
    }

    private async Task<AirportsListAndFormModel> _CreateAirportsListAndFormModel(AirportDTO airportDTO)
    {
        var airports = await this._airportService
           .GetAll()
           .ToModel()
           .ToListAsync();

        return new AirportsListAndFormModel(airports, airportDTO);
    }
}

AirlinesWeb/Controllers/FlightsController.cs
using Airlines.Business.DTOs;
using Airlines.Business.Interfaces;
using AirlinesWeb.Extensions;
using AirlinesWeb.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AirlinesWeb.Controllers;
public class FlightsController : Controller
{
    private readonly IFlightService _flightService;
    public FlightsController(IFlightService flightService)
    {
        this._flightService = flightService;
    }
    public async Task<IActionResult> Index(FlightDTO flightDTO, string? search)
    {
        return View(await _CreateFlightListAndFormModel(flightDTO));
    }

    [HttpPost]
    public async Task<IActionResult> Index([FromForm] FlightDTO flightDTO)
    {
        if (!ModelState.IsValid)
        {
            return View(await _CreateFlightListAndFormModel(flightDTO));
        }

        try
        {
            await this._flightService.AddFlight(flightDTO);
        }
        catch (Exception e)
        {
            ViewData["errMessage"] = e.Message;
        }

        return View(await _CreateFlightListAndFormModel(new FlightDTO()));
    }

    private async Task<FlightListAndFormModel> _CreateFlightListAndFormModel(FlightDTO flightDTO)
    {
        var flights = await this._flightService
            .GetAll()
            .ToModel()
            .ToListAsync();

        return new FlightListAndFormModel(flights, flightDTO);
    }
}

AirlinesWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Rise Airlines - @ViewData["Title"]</title>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/styles.css" asp-append-version="true" />
    <link rel="icon" type="image/x-icon" href="~/favicon.ico" asp-append-version="true">
</head>
<body>
    <header class="header">
        <div class="logo-wrapper">
            <a class="logo link" asp-controller="Home" asp-action="Index">
                <h1 class="link">Rise Airlines</h1>
                <img class="logo-img" src="~/assets/header-plane.png" alt="logo">
            </a>
        </div>
        <partial name="_MainNavigationPartial" />
    </header>
    <div class="container">
        <main role="main" class="main">
            @RenderBody()
        </main>
    </div>
    <footer class="footer">
        <p>Rise Airlines 2024 &copy;</p>
    </footer>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

AirlinesWeb/Views/Shared/_MainNavigationPartial.cshtml
<nav class="nav">
    <ul class="nav__items">
        <li><a class="@(Context.Request.Path == "/Airports" ? "orange-link" : "") nav__link link" asp-controller="Airports" asp-action="Index">Airports</a></li>
        <li><a class="@(Context.Request.Path == "/Airlines" ? "orange-link" : "") nav__link link" asp-controller="Airlines" asp-action="Index">Airlines</a></li>
        <li><a class="@(Context.Request.Path == "/Flights" ? "orange-link" : "") nav__link link" asp-controller="Flights" asp-action="Index">Flights</a></li>
    </ul>
</nav>